server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ChatIA?useSSL=false&serverTimezone=UTC
    username: root
    password:       # tu contraseña aquí
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092

# Redis Cloud
redis:
  host: redis-17140.c308.sa-east-1-1.ec2.redns.redis-cloud.com
  port: 17140
  password: nG7WnuToMJBBpHDHwiv1HuVyCS2fx4tB

kafka:
  topic:
    chat: chat-messages

management:
  endpoints:
    web:
      exposure:
        include: health
